## Course 'Getting and Cleaning Data'
## Johns Hopkins University
## Coursera
## Project 1 'Accelerometers from the Samsung Galaxy S smartphone'

## Task to perform
## Merges the training and the test sets to create one data set.
## Extracts only the measurements on the mean and standard deviation for each measurement. 
## Uses descriptive activity names to name the activities in the data set
## Appropriately labels the data set with descriptive variable names. 
## Creates a second, independent tidy data set with the average of each variable for each activity and each subject. 

options (warn=-1)

## Loading data
xtest <- read.table('./UCI HAR Dataset/test/X_test.txt', header = FALSE)
ytest <- read.table('./UCI HAR Dataset/test/Y_test.txt', header = FALSE)
stest <- read.table('./UCI HAR Dataset/test/subject_test.txt', header = FALSE)

xtrain <- read.table('./UCI HAR Dataset/train/X_train.txt', header = FALSE)
ytrain <- read.table('./UCI HAR Dataset/train/Y_train.txt', header = FALSE)
strain <- read.table('./UCI HAR Dataset/train/subject_train.txt', header = FALSE)

# Merges the training and the test sets to create one data set.
## Binding data
test <- cbind(ytest, stest, source="test", xtest)
train <- cbind(ytrain, strain, source="train", xtrain)

library(data.table)
data <- rbindlist(list(test, train))

## Cleaning unused object from memory
rm(xtest)
rm(ytest)
rm(stest)
rm(xtrain)
rm(ytrain)
rm(strain)
rm(test)
rm(train)

# Appropriately labels the data set with descriptive variable names.
## Asigning names to attributes of 'data'
features <- read.table('./UCI HAR Dataset/features.txt', header = FALSE)

## Assign the proper names to the attributes in 'data'
names <- rep("",length(names(data)))
for (i in 1:length(names(data))) {
  if (i == 1) names[i] = "TestLabel"
  else if (i == 2) names[i] = "Subject"
  else if (i == 3) names[i] = "Source"
  else names[i] = as.character(features[i-3, 2])
}
setnames(data, names)
rm(i)
rm(names)

#  Extracts only the measurements on the mean and standard deviation for each measurement.
## Extract only attributes related to mean and standar deviation
ms <- features[grepl("mean", features$V2) | grepl("Mean", features$V2) | grepl("std", features$V2), ]
data <- data[, c("TestLabel", "Subject", "Source", as.character(ms$V2)), with = FALSE]
names(data) <- make.names(names(data))
rm(features)
rm(ms)

# Uses descriptive activity names to name the activities in the data set
TestLabels <- read.table('./UCI HAR Dataset/activity_labels.txt', header = FALSE)
names(TestLabels) <- c("TestLabel", "TestName")

data <- merge(TestLabels, data, by = "TestLabel")
rm(TestLabels)

# Creates a second, independent tidy data set with the average of each variable for each activity and each subject.
data2 <- aggregate(data,by=list(SubjectA = data$Subject, TestNameA = data$TestName, TestLabelA =data$TestLabel, SourceA = data$Source), mean)
## Remove the duplicate columns generated by passing the whole 'data' object to aggregate instead of each column each time
data2 <- data2[ , !(names(data2) %in% c("TestLabel", "TestName", "Subject", "Source"))]
## Order de dataset by Test-Source-Subject
data2 <- data2[order(data2$TestLabelA, data2$SourceA, data2$SubjectA),] 

## Creating the complete output file and the tidy averaged file to upload in Coursera
write.table(data, "./completedata.txt", sep="\t")
write.table(data2, "./tidydata.txt", sep="\t")